---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    monitoring: prometheus-agent
    # Prometheus will discover service monitors with label monitoring: prometheus-agent in monitoring namespace